### ISSUE TITLE
Ctrl-S save should probably use Cmd-S on OSX?

### ISSUE THREAD

**Issue by bitinn** [hogashi/twitterOpenOriginalImage#1]
I am not sure if you can hook onto `Cmd-S` without causing undesirable side-effect, Maybe a simple `Enter` to save might be easier?

**Comment by bitinn** [comment]
And note that Chrome has a setting if a tab launch more than 1 download in parallel, it will prompt user.

Go to Chrome Settings and search for *Automatic Download*, you will get what I mean.

**Comment by hogashi** [comment]
Uh... I've forgotten OSX. Maybe I can hook `Cmd-S` with the property of `meta-key`. However, I don't have OSX machine so it will take time... I'll try to add it somehow.

And about the prompt, it indeed appears in that situation. But I can't recognize what the matter is. (Did you press for about two second or more?) If you don't mind, would I ask the detail situation?

Thanks to your suggest :)

**Comment by bitinn** [comment]
Just a quick note: for `cmd` you need metaKey:

https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/metaKey

**Comment by hogashi** [comment]
Wow, thanks a lot!  I'll check it.

Oh, I see, the delays... Perhaps I can correct it but I'm not sure.

**Comment by hogashi** [comment]
note: `navigator.userAgent` for OS discrimination

**Comment by hogashi** [comment]
Now, Cmd-S will work like as Ctrl-S in this extension.
Thanks a lot, @bitinn !
