### ISSUE TITLE
Is it possible to communicate with SaveIn Plugin?

### ISSUE THREAD

**Issue by librix** [hogashi/twitterOpenOriginalImage#69]
Excuse me, because I don't know this code very well, so I want to ask a question.
I want to download pictures using the [SaveIn plugin](https://github.com/gyng/save-in/), since I can save pics in different folders. but the downloaded pictures are not original.
Therefore, I found a plugin that can modify the URL to the original image address - [twitter画像原寸ボタン](https://github.com/hogashi/twitterOpenOriginalImage) which is written by you.
So I thought after processing each URL, I can call the SaveIn Plugin to save pictures with category folder and wait for the download to complete. Then proceed to the next URL.

I notices [the instructions of SaveIn plugin to be called by other plugins](https://github.com/gyng/save-in/wiki/Use-with-Foxy-Gestures).
So I want to ask, is it possible to communicate with SaveIn Plugin as described above in a part of the code of this plugin?

Attachment1: the use of SaveIn Plugin.
![image](https://user-images.githubusercontent.com/10742127/74009684-b9eaad00-49be-11ea-939c-a450f0cce4a9.png)

**Comment by hogashi** [comment]
@librix Thanks to your comment to this repo and I'm so sorry for being late to reply.

First, I won't write code for downloading images any more than now on this extension. However, there are some way to do like that (without this extension). So, it might be possible.

I have written this script that is probably able to be used as Foxy Gestures user script: https://gist.github.com/hogashi/11303cf67546644476bd1a533e89c6f9 This sends original-image URL to save-in extension.

You can use this script on your browser. Note that this is unsupported script (use on your own responsibility) and I won't maintenance it.

**Comment by hogashi** [comment]
I will close this issue.  I hope it helps.
